namespace: buluma
name: ara_collection
version: 0.1.1
readme: README.md
authors:
  - ARA Records Ansible (https://github.com/ansible-community/ara)
description: A Collection of Ara roles.
license_file: LICENSE
tags: ara
repository: https://github.com/buluma/ara-collection
documentation: https://github.com/buluma/ara-collection
homepage: https://ara.recordsansible.org
issues: https://github.com/buluma/ara-collection/issues
